### PR TITLE
Add task to install java variable is not defined

### PR DESCRIPTION
**Pull request by rbojja1**
Added task to install java if tarball url variable is not defined

### CODE REVIEW

**Review by rbojja1 — COMMENTED** [review]
Added task to install java package if tarball url variable is not specified

**Review by alphapseudo — CHANGES_REQUESTED** [review]
Since this adds another path and behavior, we may want to update the `README` to reflect this additional installation path for SLES.

**Review by rbojja1 — COMMENTED** [review]
updated readme

**Review by alphapseudo — APPROVED** [review]
lgtm

**Pull request merged**
